# OUT LEFT JOIN IN - OUT INNER JOIN IN
# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_OUTS O
# WHERE O.ANIMAL_ID NOT IN (SELECT I.ANIMAL_ID FROM ANIMAL_INS I);
SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I
ON O.ANIMAL_ID=I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL;